### ISSUE TITLE
If result of query is just one column JPA returns a List<String> instead of List<Object[]>

### ISSUE THREAD

**Issue by simasch** [72services/qlrm#16]
java.lang.ClassCastException: java.lang.String cannot be cast to [Ljava.lang.Object;
	at org.qlrm.mapper.JpaResultMapper.list(JpaResultMapper.java:34)
	at org.qlrm.executor.JpaQueryExecutor.executeSelect(JpaQueryExecutor.java:21)

**Comment by babo3yong2** [comment]
i have same issue.
just one column makes error
is this not fixed?

 java.lang.String cannot be cast to [Ljava.lang.Object;
at org.qlrm.mapper.JpaResultMapper.list(JpaResultMapper.java:40) ~[qlrm-3.0.1.jar:na]

**Comment by simasch** [comment]
@babo3yong2 Which version are you using?
And how does the query look like you try to execute?

**Comment by babo3yong2** [comment]
i used 3.0.1 version

for example, query is like "select position_id from position"

**Comment by simasch** [comment]
And how does the object look like you want to create?

**Comment by babo3yong2** [comment]
### execute query
```java 
JpaResultMapper jpaResultMapper = new JpaResultMapper();
return jpaResultMapper.list(executeQuery, MidTermStationDTO.class);
```

### Object
```java
@Getter
@Setter
@AllArgsConstructor
@ToString
public class MidTermStationDTO {
    private String position_id;
}
```

**Comment by simasch** [comment]
I cannot reproduce your problem.

Can you please create a minimal reproducible example on GitHub? Thank you

**Comment by babo3yong2** [comment]
i make simple issue. check please


https://github.com/babo3yong2/qlrm_example
-------
http://localhost:8099/hello_one -> error
http://localhost:8099/hello_two -> ok
-------

thank you for your help.

**Comment by simasch** [comment]
Thanks. I can reproduce the issue now.
The Hibernate behavior is not the same if selecting only one row or multiple rows.

**Comment by simasch** [comment]
@babo3yong2
Version 3.0.4 has been released with the fix

**Comment by babo3yong2** [comment]
@simasch 
thank you so much
it works
